//
// Created by rodri on 05-07-2025.
//

#ifndef DETECCION_DE_PATRONES_EN_MULTIPLES_ARCHIVOS_CARGARDOCUMENTOS_H
#define DETECCION_DE_PATRONES_EN_MULTIPLES_ARCHIVOS_CARGARDOCUMENTOS_H

#endif //DETECCION_DE_PATRONES_EN_MULTIPLES_ARCHIVOS_CARGARDOCUMENTOS_H
